### ISSUE TITLE
Add support for Infura to access ethereum network.

### ISSUE THREAD

**Issue by devender-yadav** [Impetus/eth-jdbc-connector#3]
[Infura](https://infura.io/) is an easy way to start with ethereum without doing any setup. 

I believe we don't need any changes. It will be covered in current RPC connection code.

https://github.com/Impetus/eth-jdbc-connector/blob/master/eth-jdbc-driver/src/main/java/com/impetus/eth/jdbc/EthConnection.java#L107

Need to pass infura endpoint (`https://mainnet.infura.io/<your-token>`) in  `httpUrl`.

**Comment by devender-yadav** [comment]
Some changes will be required since we are fetching hostname and port in case of RPC connection.

**Comment by ashishkshukla** [comment]
@devender-yadav we have added support for infura. you can checkout the latest code and try it.
